cd /sdcard/download/human
node hp
node hp-proxy
cd /sdcard/download/somnia
node main
cd /sdcard/download/monad
npm start
cd /sdcard/download/magic
node magic
cd /sdcard/download/teneo
node teneo
node index
cd /sdcard/download/monad
npm start
cd /sdcard/download/teneo
node teneo
cd /sdcard/download/human
node hp
cd /sdcard/download/magic
node magic
cd /sdcard/download/nacki
cd /sdcard/download/nacky
node nacki
cd /sdcard/download/nodego
node go
cd /sdcard/download/somnia
node main
cd /sdcard/download/nodego
node go
cd /sdcard/download/teneo
node tenwo
node teneo
cd /sdcard/download/3doa
cd /sdcard/download/3dos
node dc
cd /sdcard/download/monad
npm start
node dc
cd /sdcard/download/magic
node magic
cd /sdcard/download/monad
npm start
cd /sdcard/download/somnia
node main
cd /sdcard/download/nodego
node go
cd /sdcard/download/phq
cd /sdcard/download/pha
npm start
npm install https-proxy-agent
npm start
cd /sdcard/download/monad2
node dc2
cd /sdcard/download/0g
npm start
cd /sdcard/download/3dos
node dc
